# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Complete-file counts for the pinned Nemotron blend revision."""

NEMOTRON_COUNTS = {
    "revision": "79f8eda15ea12e1adf7bb14dcb338a29d391b80e",
    "swe_gym_revision": "bb94ed9e39bbeb96a7fcbfb533b80f25a7fd59cb",
    "swe_attribution": (
        "SWE-Gym records match instance_id membership in SWE-Gym/SWE-Gym; remaining SWE records are "
        "attributed to SWE-rebench-V2 by the blend card exhaustive two-source composition."
    ),
    "blends": {
        "rlvr1": {
            "total": 98424,
            "sha256": "b73d72788ecf13ab15457ea475f4ee619eccb1a6c0e211be999ffcf835c10ccf",
            "groups": [
                {
                    "dataset": "language_mixing_hs3_ultra_genrm_fmt",
                    "swe_source": "",
                    "count": 4795,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "ultra_sft_step3200_abstention",
                    "swe_source": "",
                    "count": 4025,
                    "agents": ["abstention_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_calendar_v2",
                    "swe_source": "",
                    "count": 910,
                    "agents": ["calendar_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_comp_coding",
                    "swe_source": "",
                    "count": 7929,
                    "agents": ["code_gen_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_instruction_following",
                    "swe_source": "",
                    "count": 11828,
                    "agents": ["instruction_following_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_jailbreak",
                    "swe_source": "",
                    "count": 2861,
                    "agents": [
                        "jailbreak_engagement_with_disclaimer",
                        "jailbreak_hard_refusal_no_redirection",
                        "jailbreak_hard_refusal_with_helplines",
                        "jailbreak_refusal_with_explanation",
                    ],
                },
                {
                    "dataset": "ultra_sft_step3200_lean",
                    "swe_source": "",
                    "count": 902,
                    "agents": ["math_formal_lean_refinement_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_cot",
                    "swe_source": "",
                    "count": 4776,
                    "agents": ["math_with_judge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_tir",
                    "swe_source": "",
                    "count": 5917,
                    "agents": ["ns_tools_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_multichallenge_len40k",
                    "swe_source": "",
                    "count": 4028,
                    "agents": ["multichallenge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_inductive",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["nvarc_inductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_transductive",
                    "swe_source": "",
                    "count": 2069,
                    "agents": ["nvarc_transductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_reasoning_gym",
                    "swe_source": "",
                    "count": 2089,
                    "agents": ["reasoning_gym_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa_cot_rima_new",
                    "swe_source": "",
                    "count": 2077,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_structured_outputs_v2",
                    "swe_source": "",
                    "count": 2080,
                    "agents": ["structured_outputs_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_swe_pivot_len40k",
                    "swe_source": "SWE-Gym/SWE-Gym",
                    "count": 2838,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_swe_pivot_len40k",
                    "swe_source": "nebius/SWE-rebench-V2",
                    "count": 11060,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_tau_pivot",
                    "swe_source": "",
                    "count": 20035,
                    "agents": ["single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_toolcall_schema",
                    "swe_source": "",
                    "count": 4011,
                    "agents": ["toolcall_schema_single_step_tool_use_with_argument_comparison_agent"],
                },
            ],
        },
        "rlvr2": {
            "total": 99116,
            "sha256": "fc3987d28bc8cd942c9012388dd25808582f5d41b3d79e9514f90c574b23dfd3",
            "groups": [
                {
                    "dataset": "language_mixing_hs3_ultra_genrm_fmt",
                    "swe_source": "",
                    "count": 4757,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "ultra_sft_step3200_abstention",
                    "swe_source": "",
                    "count": 4025,
                    "agents": ["abstention_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_calendar_v2",
                    "swe_source": "",
                    "count": 910,
                    "agents": ["calendar_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_comp_coding",
                    "swe_source": "",
                    "count": 7929,
                    "agents": ["code_gen_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_ds2_freeform",
                    "swe_source": "",
                    "count": 1392,
                    "agents": ["freeform_formatting_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_ds3_citation",
                    "swe_source": "",
                    "count": 1403,
                    "agents": ["citation_format_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_instruction_following",
                    "swe_source": "",
                    "count": 10409,
                    "agents": ["instruction_following_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_jailbreak",
                    "swe_source": "",
                    "count": 2861,
                    "agents": [
                        "jailbreak_engagement_with_disclaimer",
                        "jailbreak_hard_refusal_no_redirection",
                        "jailbreak_hard_refusal_with_helplines",
                        "jailbreak_refusal_with_explanation",
                    ],
                },
                {
                    "dataset": "ultra_sft_step3200_lean",
                    "swe_source": "",
                    "count": 902,
                    "agents": ["math_formal_lean_refinement_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_cot",
                    "swe_source": "",
                    "count": 4776,
                    "agents": ["math_with_judge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_tir",
                    "swe_source": "",
                    "count": 5917,
                    "agents": ["ns_tools_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_multichallenge_len40k",
                    "swe_source": "",
                    "count": 4028,
                    "agents": ["multichallenge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_inductive",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["nvarc_inductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_transductive",
                    "swe_source": "",
                    "count": 2069,
                    "agents": ["nvarc_transductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_rdkit",
                    "swe_source": "",
                    "count": 1403,
                    "agents": ["rdkit_chemistry_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_reasoning_gym",
                    "swe_source": "",
                    "count": 1385,
                    "agents": ["reasoning_gym_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa_cot_rima_new",
                    "swe_source": "",
                    "count": 2077,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_structured_outputs_v2",
                    "swe_source": "",
                    "count": 682,
                    "agents": ["structured_outputs_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_structured_outputs_v3",
                    "swe_source": "",
                    "count": 1398,
                    "agents": ["structured_outputs_v3_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_swe_pivot_len40k",
                    "swe_source": "SWE-Gym/SWE-Gym",
                    "count": 2838,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_swe_pivot_len40k",
                    "swe_source": "nebius/SWE-rebench-V2",
                    "count": 11060,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_tau_pivot",
                    "swe_source": "",
                    "count": 20035,
                    "agents": ["single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_toolcall_schema",
                    "swe_source": "",
                    "count": 2666,
                    "agents": ["toolcall_schema_single_step_tool_use_with_argument_comparison_agent"],
                },
            ],
        },
        "mopd": {
            "total": 85980,
            "sha256": "c6c94da041c6ef2e2e7b057f10817418f134ed46a33a274eede892fc089f0f28",
            "groups": [
                {
                    "dataset": "agent:swe_pivot_single_step_tool_use_with_argument_comparison_agent",
                    "swe_source": "SWE-Gym/SWE-Gym",
                    "count": 1884,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "agent:swe_pivot_single_step_tool_use_with_argument_comparison_agent",
                    "swe_source": "nebius/SWE-rebench-V2",
                    "count": 5307,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "hs3_en",
                    "swe_source": "",
                    "count": 1281,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "hs3_multi",
                    "swe_source": "",
                    "count": 962,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "hs3_multiturn",
                    "swe_source": "",
                    "count": 1243,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "makeshn_ultra_v3_ipi_train",
                    "swe_source": "",
                    "count": 2000,
                    "agents": ["indirect_prompt_injection_simple_agent"],
                },
                {
                    "dataset": "safety_en",
                    "swe_source": "",
                    "count": 629,
                    "agents": ["genrm_simple_agent", "genrm_simple_agent_reasoning_off"],
                },
                {
                    "dataset": "swe_pivot_len40k",
                    "swe_source": "SWE-Gym/SWE-Gym",
                    "count": 860,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "swe_pivot_len40k",
                    "swe_source": "nebius/SWE-rebench-V2",
                    "count": 3903,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_abstention",
                    "swe_source": "",
                    "count": 4025,
                    "agents": ["abstention_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_calendar_v2",
                    "swe_source": "",
                    "count": 910,
                    "agents": ["calendar_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_comp_coding",
                    "swe_source": "",
                    "count": 7929,
                    "agents": ["code_gen_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_instruction_following",
                    "swe_source": "",
                    "count": 10409,
                    "agents": ["instruction_following_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_jailbreak",
                    "swe_source": "",
                    "count": 2861,
                    "agents": [
                        "jailbreak_engagement_with_disclaimer",
                        "jailbreak_hard_refusal_no_redirection",
                        "jailbreak_hard_refusal_with_helplines",
                        "jailbreak_refusal_with_explanation",
                    ],
                },
                {
                    "dataset": "ultra_sft_step3200_lean",
                    "swe_source": "",
                    "count": 902,
                    "agents": ["math_formal_lean_refinement_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_cot",
                    "swe_source": "",
                    "count": 4776,
                    "agents": ["math_with_judge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_math_tir",
                    "swe_source": "",
                    "count": 5917,
                    "agents": ["ns_tools_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_multichallenge_len40k",
                    "swe_source": "",
                    "count": 4028,
                    "agents": ["multichallenge_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_inductive",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["nvarc_inductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_nvarc_transductive",
                    "swe_source": "",
                    "count": 2069,
                    "agents": ["nvarc_transductive_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_rdkit",
                    "swe_source": "",
                    "count": 1403,
                    "agents": ["rdkit_chemistry_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_reasoning_gym",
                    "swe_source": "",
                    "count": 1385,
                    "agents": ["reasoning_gym_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa",
                    "swe_source": "",
                    "count": 2097,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_stem_mcqa_cot_rima_new",
                    "swe_source": "",
                    "count": 2077,
                    "agents": ["mcqa_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_structured_outputs_v2",
                    "swe_source": "",
                    "count": 682,
                    "agents": ["structured_outputs_simple_agent"],
                },
                {
                    "dataset": "ultra_sft_step3200_toolcall_schema",
                    "swe_source": "",
                    "count": 2666,
                    "agents": ["toolcall_schema_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_v3_agentic_rl_step73_citation_format_v2",
                    "swe_source": "",
                    "count": 250,
                    "agents": ["citation_format_simple_agent"],
                },
                {
                    "dataset": "ultra_v3_agentic_rl_step73_freeform_text_v2",
                    "swe_source": "",
                    "count": 250,
                    "agents": ["freeform_formatting_simple_agent"],
                },
                {
                    "dataset": "ultra_v3_agentic_rl_step73_structured_outputs_v2",
                    "swe_source": "",
                    "count": 10000,
                    "agents": ["structured_outputs_v3_simple_agent"],
                },
                {
                    "dataset": "ultra_v3_agentic_rl_step73_swe_pivot_v1_len40k",
                    "swe_source": "SWE-Gym/SWE-Gym",
                    "count": 246,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
                {
                    "dataset": "ultra_v3_agentic_rl_step73_swe_pivot_v1_len40k",
                    "swe_source": "nebius/SWE-rebench-V2",
                    "count": 932,
                    "agents": ["swe_pivot_single_step_tool_use_with_argument_comparison_agent"],
                },
            ],
        },
    },
}
